# Generated by Django 2.2.2 on 2019-07-26 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190726_1950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mymodels',
        ),
        migrations.RenameField(
            model_name='articlecolumn',
            old_name='cloumn',
            new_name='column',
        ),
        migrations.AlterField(
            model_name='articlecolumn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_column', to=settings.AUTH_USER_MODEL),
        ),
    ]
