# Generated by Django 2.2.2 on 2019-09-05 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0009_articlepost_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='user_dislike',
            field=models.ManyToManyField(blank=True, related_name='articles_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
