# Generated by Django 2.2.2 on 2019-09-04 02:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='slug',
            field=models.SlugField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AlterIndexTogether(
            name='blogarticles',
            index_together={('id', 'slug')},
        ),
    ]
